export type Provenance = "self-reported" | "measured" | "sample" | "ai";

export const provenanceLabels: Record<Provenance, string> = {
  "self-reported": "Self-reported",
  measured: "Measured",
  sample: "Sample",
  ai: "AI wording",
};

/**
 * Provenance badges. Every data surface must be able to answer "where did
 * this number/text come from" at a glance (code-standards.md).
 */
export function provenanceBadge(kind: Provenance): { label: string; className: string; title: string } {
  switch (kind) {
    case "self-reported":
      return {
        label: provenanceLabels[kind],
        className: "border-sage-300 bg-sage-50 text-sage-800",
        title: "You entered this yourself.",
      };
    case "measured":
      return {
        label: provenanceLabels[kind],
        className: "border-sky-200 bg-sky-50 text-sky-900",
        title: "Computed from your actual audio by your device. Descriptive only — it does not diagnose anything.",
      };
    case "sample":
      return {
        label: provenanceLabels[kind],
        className: "border-amber-300 bg-amber-50 text-amber-900",
        title: "Fictional example data, not your entries.",
      };
    case "ai":
      return {
        label: provenanceLabels[kind],
        className: "border-violet-200 bg-violet-50 text-violet-900",
        title: "Wording generated by AI. Check it against your own entries.",
      };
  }
}
